CREATE TABLE `DTL_CD` (
`IDX` int(11) NOT NULL AUTO_INCREMENT,
`CODE` varchar(100) NOT NULL,
`GRP_CD` varchar(100) NOT NULL,
`CODE_TITLE` varchar(200) NOT NULL,
`CODE_VALUE` varchar(200) NOT NULL,
`CODE_ATTR1` varchar(200) DEFAULT NULL,
`CODE_ATTR2` varchar(200) DEFAULT NULL,
`CODE_ATTR3` varchar(200) DEFAULT NULL,
`DEL_YN` enum('Y','N') NOT NULL DEFAULT 'N',
`USE_YN` enum('Y','N') NOT NULL DEFAULT 'Y',
PRIMARY KEY (`IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `ATTACK_DECK` (
`ATTACK_ID` uuid NOT NULL,
`DEFENCE_ID` uuid DEFAULT NULL,
`MONSTER_A` uuid DEFAULT NULL,
`MONSTER_B` uuid DEFAULT NULL,
`MONSTER_C` uuid DEFAULT NULL,
`DECK_DESC` varchar(1000) DEFAULT NULL,
`INPUT_ID` uuid DEFAULT NULL,
`INPUT_DT` datetime(6) NOT NULL DEFAULT current_timestamp(6),
`UPDATE_ID` uuid DEFAULT NULL,
`UPDATE_DT` datetime(6) DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
PRIMARY KEY (`ATTACK_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `MEMBERS` (
`MEMBER_ID` uuid NOT NULL,
`MEMBER_EMAIL` varchar(200) NOT NULL,
`MEMBER_NAME` varchar(100) NOT NULL,
`MEMBER_PW` varchar(500) NOT NULL,
`MEMBER_LEVEL` int(11) NOT NULL DEFAULT 0,
`REG_CODE` varchar(200) DEFAULT NULL,
`LOGIN_CNT` int(11) NOT NULL DEFAULT 0,
`STATUS` varchar(100) NOT NULL DEFAULT 'CONFIRM',
`REFRESH_TOKEN` varchar(500) DEFAULT NULL,
`INPUT_DT` datetime(6) NOT NULL DEFAULT current_timestamp(6),
`LOGIN_DT` datetime DEFAULT NULL,
PRIMARY KEY (`MEMBER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `MEMBER_LOG` (
`LOG_IDX` int(11) NOT NULL AUTO_INCREMENT,
`MEMBER_ID` uuid DEFAULT NULL,
`LOG_TYPE` varchar(100) DEFAULT NULL,
`LOG_CONTENT` varchar(200) DEFAULT NULL,
`INPUT_DT` datetime(6) NOT NULL DEFAULT current_timestamp(6),
PRIMARY KEY (`LOG_IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `DEFENCE_DECK` (
`MONSTER_A` uuid DEFAULT NULL,
`MONSTER_B` uuid DEFAULT NULL,
`MONSTER_C` uuid DEFAULT NULL,
`DECK_DESC` varchar(1000) DEFAULT NULL,
`INPUT_ID` uuid DEFAULT NULL,
`INPUT_DT` datetime DEFAULT current_timestamp(),
`UPDATE_ID` uuid DEFAULT NULL,
`UPDATE_DT` datetime DEFAULT NULL ON UPDATE current_timestamp(),
`DEFENCE_ID` uuid NOT NULL,
PRIMARY KEY (`DEFENCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `MONSTER` (
`MONSTER_ID` uuid NOT NULL,
`MONSTER_DESC` varchar(200) NOT NULL,
`INPUT_ID` uuid DEFAULT NULL,
`INPUT_DT` datetime DEFAULT NULL,
`UPDATE_ID` uuid DEFAULT NULL,
`UPDATE_DT` datetime DEFAULT NULL,
`MONSTER_NAME` varchar(100) NOT NULL,
`MONSTER_TYPE` varchar(200) NOT NULL,
PRIMARY KEY (`MONSTER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

CREATE TABLE `GRP_CD` (
`IDX` int(11) NOT NULL AUTO_INCREMENT,
`GROUP_CODE_ID` varchar(100) DEFAULT NULL,
`GROUP_TITLE` varchar(100) DEFAULT NULL,
`GROUP_VALUE` varchar(100) DEFAULT NULL,
`GROUP_ATTR1` varchar(200) DEFAULT NULL,
`GROUP_ATTR2` varchar(200) DEFAULT NULL,
`INPUT_ID` uuid DEFAULT NULL,
`INPUT_DT` datetime(6) NOT NULL DEFAULT current_timestamp(6),
`UPDATE_ID` uuid DEFAULT NULL,
`UPDATE_DT` datetime(6) DEFAULT current_timestamp(6) ON UPDATE current_timestamp(6),
`DEL_YN` enum('Y','N') NOT NULL DEFAULT 'N',
`USE_YN` enum('Y','N') NOT NULL DEFAULT 'Y',
PRIMARY KEY (`IDX`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

